/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NuxtAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    NuxtApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    NuxtButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    NuxtCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    NuxtForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    NuxtFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    NuxtIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    NuxtInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    NuxtTabs: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
